
import Head from "next/head";
import aboutStyles from "../styles/about/About.module.css";
import Image from 'next/image';
import Eagel from '../assets/images/flying-eagle.gif'
import Kangaroo from '../assets/images/giphy.gif'
import Nested from '../assets/images/unnamed.gif'
import Assessment from '../assets/images/check-list.png'
import Development from '../assets/images/developing.png'
import Planning from '../assets/images/planning.png'
import Implementation from '../assets/images/schedule.png'
import Evaluation from '../assets/images/evaluation.png'
import Star from '../assets/images/star.png'
import {
  FaLongArrowAltRight
} from "react-icons/fa";


const aboutus = () => {
  return (
    <>
      <div>
        <Head>
          <title>Orgeon | About Us</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="./forhome.png" />
        </Head>
        <div className={aboutStyles.briefhistory}>
          <h3>Orgeonofstars</h3>
          <h4>Brief History</h4>
          <p className={aboutStyles.dissolution}>
            I once encountered a 9-year-old boy by name Nii, he tasked himself
            to collect trash from my office building at Nungua. In my
            perspective, I felt it was wrong for a child to be doing such duties
            when he has to be in school learning. Through a short conversation
            with Nii, I learnt that he had do this for his daily feedings and
            money for school. I felt the need to support him, so I decided to
            provide him with daily financial support so he can focus on school.
            Our little deal went on for about 3 months and Nii just disappeared
            without a trace. Did my best to locate him but all efforts were in
            vain. Months went by and I chanced on Nii again, he was doing his
            trash collecting rounds. After a short conversation he made it known
            that his mom passed away and his dad distributed them off to his
            relatives. Living with his relatives was challenging and he decided
            to start his trash collecting job again. Meeting Nii again in this
            condition, saddened my heart, I felt the need to create an
            organization which will consistently aid vulnerable children in such
            situations. Hence the birth of Orgeon of Stars. ORgeon of Stars is a
            God driven purpose, which goal is to aid the less privilege child
            through nurturing, guidance and providing life basic needs. In turn
            we help them develop their God given potentials so they can shine
            like the stars God originally made them to be.
          </p>
          <h2>DISSOLUTION</h2>
          <p className={aboutStyles.dissolution}>
            In the event of dissolution of the organization, we grant the
            department of Social welfare permission to transfer all belongings
            or property owned by ORgeon of Stars to a Non-for profit
            organization, which carries similar goals and objectives as ours.
            Please disperse any item or belongings in our name .
          </p>
        </div>
        <div className={aboutStyles.carecontainer}>

          <div className={aboutStyles.careplans}>
            <h3 className={aboutStyles.careplantitle}>Client Plan</h3>
            <br />
            <p className={aboutStyles.careplancontent}>There are three various plans available at Orgeonofstars under which a client may fall.A client is given a plan based you their situation,age and gender.These plans include </p>
            <br /><br />
            <div className={aboutStyles.plans}>
              <div className={aboutStyles.img}>
                <Image src={Eagel} alt="care plan" width={150} height={150} />
                <h4>Eagel</h4>
              </div>
              <div className={aboutStyles.img}>
                <Image src={Kangaroo} alt="care plan" width={150} height={150} />
                <h4>Kangaroo</h4>
              </div>
              <div className={aboutStyles.img}>

                <Image src={Nested} alt="care plan" width={150} height={150} />
                <h4>Nested</h4>
              </div>
            </div>
            <br /><br />
            <h3 className={aboutStyles.careplantitle}>Client Process</h3>
            <br />
            <p>After a plan to allocated to the client,he or she has to go through a six-stage assessment process in order to become a successful client.One can become a client if he or she passes all these stages and become a star.</p>
            <br /><br />
            <div className={aboutStyles.stages}>
              <div className={aboutStyles.img}>
                <Image src={Assessment} alt="care plan" width={150} height={150} />
                <h4>1.Assessment</h4>
              </div>

              <div className={aboutStyles.img}>
                <Image src={Development} alt="care plan" width={150} height={150} />
                <h4>2.Development</h4>
              </div>
              <div className={aboutStyles.img}>
                <Image src={Planning} alt="care plan" width={150} height={150} />
                <h4>3.Planning</h4>
              </div>
              <div className={aboutStyles.img}>
                <Image src={Implementation} alt="care plan" width={150} height={150} />
                <h4>4.Implementation</h4>
              </div>
              <div className={aboutStyles.img}>
                <Image src={Evaluation} alt="care plan" width={150} height={150} />
                <h4>5.Evaluation</h4>
              </div>
              <div className={aboutStyles.img}>
                <Image src={Star} alt="care plan" width={150} height={150} />
                <h4>6.Star</h4>
              </div>

            </div>

          </div>
        </div>

      </div>
    </>
  );
};

export default aboutus;
