import AddPartner from "../components/partners/AddPartner";
import Head from "next/head";

const addpartner = () => {
  return <div>
      <Head>
        <title>Become a partner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./forhome.png" />
      </Head>
      <AddPartner />
  </div>;
};

export default addpartner;