import Link from "next/link";
import donateStyle from "../styles/donate/Donate.module.css";
import Head from "next/head";

const donate = () => {
  return (
    <>
    <Head>
        <title>Orgeon | Make Donation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./forhome.png" />
      </Head>
    <div className={donateStyle.donatecontainer}>
      <div className={donateStyle.donatebox}>
        <span>One Time Donation</span>
        <form
          action="https://www.paypal.com/cgi-bin/webscr"
          method="post"
          target="_top"
        >
          <input type="hidden" name="cmd" value="_s-xclick" />
          <input
            type="hidden"
            name="hosted_button_id"
            value="NHYKARN4U4DWJ"
          />
          <input
          className={donateStyle.paybutton}
            type="submit"
            value="Donate"
            id="butt"
            title="PayPal - The safer, easier way to pay online!"
            alt="Donate with PayPal button"
          />
        </form>

      </div>
      <div className={donateStyle.donatebox}>

        <span>Monthly Donation</span>
        <form
          action="https://www.paypal.com/cgi-bin/webscr"
          method="post"
          target="_top"
        >
          <input type="hidden" name="cmd" value="_s-xclick" />
          <input
            type="hidden"
            name="hosted_button_id"
            value="4ABS2J7M6BLVC"
          />
          <input
          className={donateStyle.paybutton}
            type="submit"
            value="Donate"
            id="butt"
            title="PayPal - The safer, easier way to pay online!"
            alt="Donate with PayPal button"
            
          />
        </form>

      </div>
    </div>
    </>
  );
};

export default donate;
