import GalleryList from "../components/gallery/GalleryLIst";
import Head from "next/head";

const gallery = ({data}) => {
  return <div>
      <Head>
        <title>Orgeon | Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./forhome.png" />
      </Head>
      <GalleryList data={data} />
  </div>;
};

export async function getServerSideProps() {
    const res = await fetch(`https://orgeonofstars.xyz/get_gallery_list`);
    const data = await res.json();
    
    return { props: { data } };
  }

export default gallery;
