import PartnersList from "../components/partners/PartnerLIst";
import Head from "next/head";
import { FaPlus } from "react-icons/fa";
import Link from "next/link";
import volunteerStyle from "../styles/volunteers/VolunteerCard.module.css";

const partners = ({data}) => {
    
  return <div>
      <Head>
        <title>Orgeon | Partners</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./forhome.png" />
      </Head>
      <Link href="/addpartner" passHref>
        <div className={volunteerStyle.addvolunteer}>
          <FaPlus />
        </div>
      </Link>
      <PartnersList data={data} />
  </div>;
};

export async function getServerSideProps() {
    const res = await fetch(`https://orgeonofstars.xyz/get_partners`);
    const data = await res.json();
    
    return { props: { data } };
  }

export default partners;
