import VolunteersList from "../components/volunteers/VolunteersList";
import Head from "next/head";
import { FaPlus } from "react-icons/fa";
import volunteerStyle from "../styles/volunteers/VolunteerCard.module.css";
import Link from "next/link";

const volunteers = ({ data }) => {
  console.log(data.get_volunteer_photo)
  return (
    <div>
      <Head>
        <title>Orgeon | Volunteers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./forhome.png" />
      </Head>
      <Link href="/addvolunteer" passHref>
        <div className={volunteerStyle.addvolunteer}>
          <FaPlus />
        </div>
      </Link>
      <VolunteersList data={data} />
    </div>
  );
};

export async function getServerSideProps() {
  const res = await fetch(`https://orgeonofstars.xyz/get_volunteers`);
  const data = await res.json();

  return { props: { data } };
}
export default volunteers;
