import volunteerStyle from "../../../styles/volunteers/VolunteerCard.module.css";
import Head from "next/head";
import { useState } from "react";
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import axios from "axios";
import styles from "../../../styles/volunteers/VolunteerCard.module.css";

const Partner = ({ p_detail }) => {
  const router = useRouter();
  const p_num = p_detail.phone;
  const [mobileNumber, setMobileNumber] = useState("");

  const handleDeleteVolunteer = (e) => {
    e.preventDefault();
    toast.success("Please wait,removing your data");
    const apiUrl = `https://orgeonofstars.xyz/delete_partner/${p_detail.id}`;
    if(mobileNumber == p_num){
        axios({
            method: "delete",
            url: apiUrl,
            headers: { "Content-Type": "multipart/form-data" },
          })
            .then(function (response) {
                setTimeout(function () {
                    router.push("/partners");
                },3000)
            })
            .catch((error) => {
              if (error.response) {
                toast.error(`${error.response.data}`);
              }
            });
    }
    else{
        toast.error("Invalid mobile number provided")
    }
  };

  return (
    <>
      <Head>
        <title>Orgeon | Partner - {p_detail.id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./forhome.png" />
      </Head>
      <div className={volunteerStyle.pmaincontainer}>
            <h2>Stop been our partner and delete all your information</h2>
        <div className={volunteerStyle.pdetailscontainer}>
          <h2>{p_detail.name}</h2>
        </div>
        <h4>Enter your mobile number</h4>
        <ToastContainer className="foo" style={{ width: "320px",fontSize: "15px" }}/>
        <form onSubmit={handleDeleteVolunteer}>
          <div className={styles.formcontrol}>
            
            <input
              required
              type="text"
              name=""
              id="mobilenumber"
              value={mobileNumber}
              onChange={(e) => setMobileNumber(e.target.value)}
              placeholder="Mobile Number"
            />
          </div>

          <br />
          <div className={styles.formcontrol}>
            <button type="submit">Delete</button>
          </div>
          <br />
        </form>
      </div>
    </>
  );
};

export const getStaticProps = async (context) => {
  const res = await fetch(
    `https://orgeonofstars.xyz/partner_detail/${context.params.id}`
  );
  const p_detail = await res.json();

  return {
    props: {
      p_detail,
    },
  };
};

export const getStaticPaths = async () => {
  const res = await fetch(`https://orgeonofstars.xyz/get_partners`);
  const partners = await res.json();
  const ids = partners.map((partner) => partner.id);
  const paths = ids.map((id) => ({ params: { id: id.toString() } }));
  return { paths, fallback: false };
};

export default Partner;
